### ISSUE TITLE
Translatable preferences

### ISSUE THREAD

**Issue by toXel** [shkcodes/Lyrically#11]
The strings in preferences.xml should also be extracted into the strings.xml so they become translatable.

I would do it but I want to ask @shkcodes if this is ok? :slightly_smiling_face:

**Comment by shkcodes** [comment]
Yep go ahead. I was planning to this. 
And thanks a lot for the translations!! Much appreciated.

**Comment by shkcodes** [comment]
Don't forget to add the German text for the preference strings. Thanks!

**Comment by shkcodes** [comment]
I've added some more files.

**Comment by toXel** [comment]
OK nice. But I think it's a better practice to not fill in the "empty translations". That way the translators can't see which strings aren't already translated in the Android Studio Translator. If you just don't add them to the values-XX files the app will load the not translated strings from the main strings.xml so there will be no difference in the app.

I hope you understand my point :smile:

**Comment by shkcodes** [comment]
Gotcha.
