### ISSUE TITLE
Open the app from lyrics panel

### ISSUE THREAD

**Issue by toXel** [shkcodes/Lyrically#15]
A possibility to open the app or settings from the lyrics panel would be very helpful.
Maybe with a long-tap/double-tap on the song title?

**Comment by shkcodes** [comment]
It used to be that way but a user requested that clicking the notification open the lyrics panel. You only need settings for the initial setup and don't need to open them very often. That's why I think I'll let it be the way it is.

**Comment by toXel** [comment]
No that's ok. I think I was not specific enough. It's a good thing that it opens the lyrics panel on notification click! I meant a long-click/double-click on the orange song title in the lyrics panel. But maybe that's a bad idea and is bloating the app because as you said: most of the time it's a one-time initial setup. So I'll close the issue.
