### ISSUE TITLE
Offline Lyrics download

### ISSUE THREAD

**Issue by keio9** [shkcodes/Lyrically#23]
When trying to download the lyrics for offline use the dialog box says "Download lyrics for 0 songs?". 

Cleared data, cache. Uninstalled, reinstalled. Tried different versions. Clicking yes to download lyrics causes the app to force close. 

It was working perfectly before I factory reset my phone. 

Thanks

**Comment by shkcodes** [comment]
Did the factory reset, by any chance, delete your songs?

**Comment by keio9** [comment]
It did.  Only lyrics in the folder now are the songs that I've played and it's cached.

**Comment by shkcodes** [comment]
Try downloading some new songs to your phone and try again.

**Comment by keio9** [comment]
No dice.  I tried on a different device. First install of both Google Play Music and Lyrically. Streamed a few songs, switched to downloaded only to verify songs were downloaded. Lyrically finds 0 songs. Clicking yes crashes app.

**Comment by shkcodes** [comment]
I guess its because Lyrically can't get a list of songs downloaded through Play Music. However, lyrics are automatically cached so you only need to strream a song once to cache it.
I can't help you any further as I don't have Play Music subscription sorry.

**Comment by keio9** [comment]
Downgrading to Beta 0.42 works on both devices.   Verified by uninstalling Google Play Music (including downloaded songs) and Lyrically. Installed GPM and Lyrically 0.42.  Everything working perfectly.

**Comment by keio9** [comment]
Would a screenshot or screen recording of the steps to reproduce the error help at all?

**Comment by shkcodes** [comment]
Nope sorry. You didn't try 0.42 earlier?

**Comment by keio9** [comment]
No. Only tried .51 and.50. Could have sworn I was running the latest version before the reset.  My mistake, all's good now. 

Great job on the app otherwise. By far best lyric app I've used on Android.

**Comment by shkcodes** [comment]
Cheers. 
By the way, no code was changed regarding the downloading of lyrics between 0.42 and 0.51/52.

**Comment by keio9** [comment]
Strange...
