### ISSUE TITLE
Project end?

### ISSUE THREAD

**Issue by DarkAbhi** [shkcodes/Lyrically#32]
Has InstaGaana project been shutdown ? May I know the reason?

**Comment by shkcodes** [comment]
We would like to inform you that InstaGaana has been shut down after receiving a cease and desist notice from Saavn. While we value your response we can't help you.

It's is entirely possible that Saavn fixed the security bug that allowed access to music URLs. 

Please send your further queries to LinuxSDA@gmail.com.
