### ISSUE TITLE
Support for Huawei G Play Mini

### ISSUE THREAD

**Issue by EnderKingHD** [shkcodes/Lyrically#33]
Hello there, I really wish this app would work on my phone, but it seems to be incompatible as on F-Droid it's greyed out and when I try a manual install it throwed an error saying there was an error while parsing the package. So please mr developer, consider adding support for my phone? ;D (Using Android 4.4.2 and EMUI 3.0

**Comment by shkcodes** [comment]
You need to be on Lollipop or above to use this app.
