### ISSUE TITLE
More of a question..possibly an issue

### ISSUE THREAD

**Issue by craigalan** [shkcodes/Lyrically#34]
Should this app be starting on it's own or does it start automatically on reboot or when music app is loaded?  I am using with Google Play.  Sometimes though it seems to start running without my opening and I haven't figured if something is triggering it to open....either that or if it's supposed to run on boot, it seems to be shutting down, because it is not always in my notification menu and other times it is.

Thank you for the app and looking forward to your reply!

Craig

**Comment by shkcodes** [comment]
First, make sure your music is stopped and there is no Lyrically notification.

i) Play music - Lyrically notification shows up - check lyrics
ii) Pause music - Lyrically notification still there but you can swipe it away to stop the service
iii) Play music - The notification which was previously dismissible is stickied until you stop the music

The notification appears when you start the music but doesn't go away when you pause it. Some users wanted to see the lyrics while their music was paused, so I implemented it this way.

I hope this clears any doubts you had!

**Comment by craigalan** [comment]
Thanks for the reply!  Very much appreciated!!
So what should happen if I stop and close the music app.  Will Lyrically stay in the notification menu until swiped away?

Craig

**Comment by shkcodes** [comment]
Lyrically relies on music being paused to make the notification dismissible. So yes, if you stop the music and close the music app, you should be able to dismiss the notification.

**Comment by craigalan** [comment]
Thank you!!

Craig

On August 23, 2017 12:38:53 AM Shashank Mishra <notifications@github.com> wrote:

Lyrically relies on music being paused to make the notification dismissible. So yes, if you stop the music and close the music app, you should be able to dismiss the notification.
