### ISSUE TITLE
Request to allow changing color

### ISSUE THREAD

**Issue by kkuhle** [shkcodes/Lyrically#37]
It would be great if we could use amoled black!

**Comment by shkcodes** [comment]
Alright I'll add a color picker soon.

**Comment by kkuhle** [comment]
Awesome! That would be perfect

**Comment by shkcodes** [comment]
Added in ad7723d57ffd36a85d7e49964a2f0908d40aa548

**Comment by kkuhle** [comment]
Great! Can't wait to give it a try when the new version is made available.

**Comment by shkcodes** [comment]
It is available [here](https://github.com/shkcodes/Lyrically/releases/tag/0.54)

**Comment by kkuhle** [comment]
The new color option is perfect.  Thanks for getting this done so quickly!
