### ISSUE TITLE
Request To Create a Privacy Policy and FAQs

### ISSUE THREAD

**Issue by Kelita** [shkcodes/Lyrically#42]
Hello, I'm Kelita. I would like to contribute to your project. I noticed your project have no Privacy Policy and FAQs, which I will like to help contribute that
A Privacy Policy allows users of the app to know about the policies regarding end-users information collection and use. 
FAQs will answer some question users might want to have and save both you and the users the stress of asking and you answering the same set of question over and over again.

I would be waiting for your reply.

**Comment by Kelita** [comment]
Okay! The Privacy Policy will simple contain details of how information of users is used and what it is used for. Then what type of users information is obtained. That if you collect personal information of users. It will also contain permissions the apps needs. 

Then how you want people to contact you either via Github or Email

**Comment by shkcodes** [comment]
Alright go ahead.

**Comment by Kelita** [comment]
So, do you collect any information? And how do you want people to contact you.

**Comment by shkcodes** [comment]
I don't collect any information.

And people can contact me at my email shkcodes@gmail.com.

**Comment by Kelita** [comment]
Okay. Thanks for the information so far. Do you also have any question in mind that you want to add to the FAQs?

**Comment by shkcodes** [comment]
Nope. I've uploaded a video on how to use the app. That should be enough.

Sorry for the late reply.

**Comment by Kelita** [comment]
Please, where is the link to the video?

**Comment by Kelita** [comment]
Hello, how are you doing? I have completed the Privacy Policy, below is a link to it. Please go through it in case there might need for corrections. 
https://docs.google.com/document/d/14pqAgj5MIVO-aPXsIo7CmC69S8S2i0UaTF7ItLEtpbQ/edit?usp=sharing

**Comment by shkcodes** [comment]
Looks great! Will we provide this as a link or should I create a file in the repository?

**Comment by Kelita** [comment]
I make a pull request; then you will merge it. That all you need to do.
