### ISSUE TITLE
[Bug] Lyrically Crashed when Downloading Lyric from Song that have Japanese Title

### ISSUE THREAD

**Issue by ditokp** [shkcodes/Lyrically#47]
**Song Title** : ドーン！やられちゃった節

**Song Artist** : Nakamura Emi

![](https://i.imgur.com/PL0dy25.png)

**How to Reproduce the bug:**
1) Open the app
2) Click Download in the top
3) It crashed when downloading that song.

**Screenshots :**
![](https://i.imgur.com/kPoyYIg.png)
![](https://i.imgur.com/oA8TWHI.png)

Lyrically can download other song from same artist like that crashed song. After crashed, I can't delete the lyrically notification, but after the device restart, the lyrically notification bar can be deleted.

**System Specs:**

Advan I4d

Android Lollipop (Not using default ROM called Idos, but using Custom ROM called Gretel U5)

Note:

I'm sorry if my English is not good enough.

**Comment by Kobberholm** [comment]
When I click Download lyrics for offline usage, it always reaches song number 53 Piece of Heaven (radio mix) - Akira and then hangs in the notification bar. The app has to be force closed to clear the notification.
This might mean that that song has finished downloading and it hangs when trying to display the name of the next song, I don't know.
This happens on version 0.53 and 0.54 alike. Both are installed from F-Droid.
I am running it in a Samsung Galaxy S8 with Android 8.0.0.

**Comment by shkcodes** [comment]
Thank you for the detailed information. I will look into it as soon as
possible.

**Comment by shkcodes** [comment]
@ditokp I have identified the issue. It is not related to fetching the lyrics. It is crashing due to a bug in update checker service. I have fixed it in Beta 0.55.

**Comment by ditokp** [comment]
@shkcodes thank you for fixing this issue
