### ISSUE TITLE
no notification on spotify, phonogram works

### ISSUE THREAD

**Issue by ghost** [shkcodes/Lyrically#48]
hey there.

problem: open spotify -> press play -> no lyrically notification in notification bar, thus, trigger does not work either, so no way to get lyrics panel to show.

lyrically does work with phonograph! but: even if I press pause in phonogram, don't kill the lyrically notification that is still opened in the background, then open spotify and play something there, then trigger lyrically, it just show's me the "old" lyrics from the song that just played in phonogram, no matter how often I refresh the panel. so to me it seems that lyrically is for some reason not getting at all that spotify is playing 🤔 

any ideas why that would be?

I'm on a Huawei P20 Pro (CLT-L29) with EMUI 9.0.0.163. Thought it could be some weird thing with my sonos wireless speaker, but doesn't make a difference when using the phone speaker... restart also doesn't change anything. I even disabled automatic battery management for lyrically before I realized it worked with phonogram, because I thought that it would maybe get killed instantly in the background or something, haha.

well, hope there is some idea about this, 'cause I've been searching for something like this for a looong time :)

**Comment by shkcodes** [comment]
Thanks for reporting it to me. I'll take a look at it soon!

**Comment by shkcodes** [comment]
Can you make sure that "Device Broadcast Status" is on in Spotify settings?

**Comment by ghost** [comment]
Oh, wow, that fixed it! Should that have been enabled by default in Spotify? Thank you so much, this is really amazing! Any way to send you a small donation?

**Comment by shkcodes** [comment]
Glad you got it working! And yes I have a PayPal. Please email (shkcodes@gmail.com) me to know the details. And thanks a lot for even considering to donate <3
