### ISSUE TITLE
Doesn't find any of my songs

### ISSUE THREAD

**Issue by moshpirit** [shkcodes/Lyrically#5]
I'm using Vanilla Music player and Lyrically 0.3 on Android 6.0.1 and doesn't find any lyrics. The same happened before.

Where does it search them?

**Comment by shkcodes** [comment]
Can you try rebooting your phone?

**Comment by moshpirit** [comment]
Still nothing :(

It's here: http://genius.com/Summoning-kor-lyrics

**Comment by shkcodes** [comment]
Can you try rebooting your phone?

**Comment by moshpirit** [comment]
The still nothing was for this. I actually need to reboot my phone to start using it

**Comment by shkcodes** [comment]
What phone do you have? I'm really sorry that it isn't working for you.

**Comment by moshpirit** [comment]
Haha don't worry, thanks a lot for your time and dedication! It's a BQ Aquaris M5 (Android 6.0.1, official ROM)

**Comment by shkcodes** [comment]
I forgot to ask, what music player are you using? I just tried it on Spotify and it works perfectly
![screenshot_20161224-223254](https://cloud.githubusercontent.com/assets/16430299/21468095/6fb6c452-ca29-11e6-9707-c4dbdd80a129.png)

**Comment by moshpirit** [comment]
I'm using Vanilla Music 1.0.46 from F-droid. I believe it's based on the ASOP music player

**Comment by shkcodes** [comment]
That is a weird bug which has been happening to some of the users. Sadly, I haven't been able to replicate it. A reboot fixes that in most cases.

**Comment by moshpirit** [comment]
I see. Then I think I'll came back when it's fixed or if you want me to test anything :) thank you so much for your great support and nice work! Merry Christmas/Happy Newton's birthday!

**Comment by shkcodes** [comment]
Same to you!

**Comment by shkcodes** [comment]
> The weird thing is that it detects something is playing but doesn't show the lyrics

Yo, I might have found a solution to this. Can you get to this stage, then without pausing your music, just change your song? Just click the next button on your music player. Does it work then?

**Comment by moshpirit** [comment]
It doesn't 😞    
Thanks anyway for working on it!

**Comment by shkcodes** [comment]
When you're at that stage, click on another song in the Vanilla Music Player. Does it work then?

**Comment by moshpirit** [comment]
Nope :\ does it depend on any Google service?

**Comment by shkcodes** [comment]
Nope. And I just tried 
> When you're at that stage, click on another song in the Vanilla Music Player
and
> Just click the next button on your music player

and it worked for me. Can you try using Phonograph from the Play Store?

**Comment by moshpirit** [comment]
I don't use any Google service so I can't install it (I searched it on F-droid and it's not there so I can't)

I torify most of my apps but Lyrically doesn't go through TOR so it shouldn't be a problem either, but maybe it relies on any other app or whatever. I'm using an official ROM though.

**Comment by shkcodes** [comment]
Alright thanks for replying so quickly. I'll keep looking.

**Comment by moshpirit** [comment]
Thank you! :)

**Comment by sunbriel** [comment]
Hey there. I have the same problem. I use Pulsar, but since I read here that you don't support it, I tried with Phonograph. Lyrically doesn't find lyrics to any of my songs, even after a reboot.

**Comment by shkcodes** [comment]
Did you try everything mentioned in this thread? Do your songs have the proper tags? Can you give me the name of the songs for which it can't find the lyrics?

**Comment by sunbriel** [comment]
Interesting. I gave it another shot today and suddenly it found lyrics to most of my songs (minus a couple of obscure ones).

**Comment by shkcodes** [comment]
Ugh. I wish I could figure out why it stops working randomly on some phones :(
Glad it works now!

**Comment by moshpirit** [comment]
Update: I'm using the last version on Android (0.42) didn't work either

**Comment by shkcodes** [comment]
Try out 0.5 both of you. I've reworked how the lyrics are shown.

**Comment by sunbriel** [comment]
Nothing above 0.31 works for me. I have to manually go to Lyrically settings to activate the window to be able to activate it system-wide. And then it just keeps loading indefinitely.

**Comment by moshpirit** [comment]
**GOOD NEWS**

I'm using Vanilla Music 1.0.47 and Lyrically 0.51 and it works!! 

I also installed the Vanilla Music lyrics search plugin (v. 1.0) but don't know how to enable it haha

Thank you so much!!

**Comment by shkcodes** [comment]
Glad it works!

**Comment by moshpirit** [comment]
Me too haha didn't close it before because of sunbriel 

Thanks a lot for the support!! :)
