### ISSUE TITLE
Lyrics

### ISSUE THREAD

**Issue by srt10coupe** [shkcodes/Lyrically#7]
where are looking the app for lyrics?

the app found 50% of my Songs not.

**Comment by shkcodes** [comment]
It goes from azlyrics -> genius -> lyrics.wikia.

If you tell me a site which has the lyrics of your songs, I'll be more than happy to add it.

**Comment by srt10coupe** [comment]
songtexte.com

**Comment by shkcodes** [comment]
Give me 3 songs whose lyrics are available on this site and not on the three others I've mentioned? I'm almost done adding songtexte.com, just need to test it a bit.

**Comment by srt10coupe** [comment]
I'll send you in the next few days ;).👍🏿

**Comment by srt10coupe** [comment]
1. http://www.songtexte.com/songtext/chumbawamba/shake-baby-shake-3cec9cf.html
2. http://www.songtexte.com/songtext/chumbawamba/pass-it-along-bcec9ce.html
3. http://www.songtexte.com/songtext/chumbawamba/hey-hey-were-the-junkies-13cec9cd.html

just a small part :)

**Comment by shkcodes** [comment]
I'm sorry but I got those without adding songtexte.com support. Can you make sure you have the proper tags on the songs?

[Proof](http://imgur.com/a/D6N2h)

**Comment by srt10coupe** [comment]
I think I have the right tags.
mp3tags https://imgur.com/gallery/6bmbP

**Comment by shkcodes** [comment]
That's weird. Can you try with one of these music players : 
Google Play Music 
Spotify
Phonograph
Shuttle
Poweramp
Rocket Player

**Comment by srt10coupe** [comment]
I have phonograph in use, after clean install cm14.1 lyrically display the lyrics 😒.

**Comment by shkcodes** [comment]
Sooo, it's working now?

**Comment by srt10coupe** [comment]
yes it works

**Comment by akshayputtaswmay** [comment]
Cn you give me an example what type should be the tags

**Comment by akshayputtaswmay** [comment]
Cn you give me an example what type should be the tags

**Comment by akshayputtaswmay** [comment]
Are the lyrics available for all the language songs
