### ISSUE TITLE
Spotify

### ISSUE THREAD

**Issue by noodlezoodle** [shkcodes/Lyrically#8]
Lyrically only download lyrics from local songs. It would be great if the app can download song lyrics played using Spotify.

**Comment by shkcodes** [comment]
Are the songs from Spotify being stored offline?

**Comment by noodlezoodle** [comment]
Yes, indeed it is stored offline. Although it said it downloaded 41 lyrics which is for my local songs, it didn't download lyrics for my 200+ songs downloaded through Spotify.

**Comment by shkcodes** [comment]
I'm afraid I might not be able to do this. I've gone through the Spotify SDK and it seems you need a premium account to fetch an account's saved tracks. And I don't have Spotify premium.

Would it be fine if I gave you an apk which caches all the Spotify songs you play? It would store each and every song you play through Spotify.

**Comment by noodlezoodle** [comment]
That would be nice. Thanks for the app btw. :)

**Comment by shkcodes** [comment]
Can you try out the latest release? Go to Settings and check the "Cache All" option.

**Comment by noodlezoodle** [comment]
Weird, I can't get it triggered lyrics on any songs. It works perfectly on previous release.

**Comment by shkcodes** [comment]
Weird indeed. Uninstall the older version and install the latest one?

**Comment by noodlezoodle** [comment]
Still the same. I can only trigger the lyrics panel in the app settings but not anywhere else.

**Comment by shkcodes** [comment]
Yep. I found out what the issue is. Will fix it tomorrow. Pretty bad mistake on my part. Whoops!

**Comment by noodlezoodle** [comment]
Yes, I'm on Lollipop and forever stuck with it. Smh

**Comment by shkcodes** [comment]
Download the latest version again. The file name should be "app-release1.apk"

**Comment by noodlezoodle** [comment]
It works perfectly now! Gonna recommend this to /r/spotify as a perfect Musixmatch alternative. Thanks a lot!

**Comment by shkcodes** [comment]
Thanks a lot! You can also get Lyrically from [F-Droid](https://f-droid.org/repository/browse/?fdid=com.shkmishra.lyrically). However, if you don't want to install F-Droid, there's already a weekly update checker in the app.
