### ISSUE TITLE
Forece close

### ISSUE THREAD

**Issue by The1andONLYdave** [shkcodes/Lyrically#9]
Hi, 
I get force-close on settings(works 1 or 2 times, then dont work till reinstalling) and when trying to download Lyrics(everytime).

Worked fine before some weeks.
Then i did started downloading Lyrics, but aborted because of slow download. Removed folder from sdcard. Upgraded Android (6 to 7.0).

Tried, dont help: 
-reinstalling App in current version
-reinstalling Version 0.22
-checking that overlay and storage permissions are granted

Amy known fixes? Can this be a android 7 related Issue?

**Comment by shkcodes** [comment]
I had this issue on my friend's phone too. I think this is because you guys have external SD cards. 

I'll look into it for the next version. Really sorry for the inconvenience. 

You can use the older version (0.11) till I find a solution. It doesn't have offline support.

**Comment by shkcodes** [comment]
Can you try version 0.31? It's working perfectly on my friend's phone.

**Comment by shkcodes** [comment]
Any update? Did the latest version work properly?

**Comment by The1andONLYdave** [comment]
Hi, Sorry i missed the notification from github. 
Tested 0.31, still force close on pressing Download. But requested storage permission at first start succesfully. 
Tried also to clear app-data and grant permissions before first start: still FC on Downloads. 
Do you have a build with a lot of logging output in Logcat for testing?

**Comment by The1andONLYdave** [comment]
Additional info(cant edit last comment on mobile):
When playing spotify and opening 0.31 lyrically FCs everytime i leave settings (whether home or back Button doesn't matter). Just opening lyrically without settings and closing make no crash but also dont display lyrics-overlay.

**Comment by shkcodes** [comment]
Uninstall the previous versions and install [this](https://github.com/shkcodes/Lyrically/releases/tag/0.4) one. It will ask for permissions when you star it. It should work properly then.

**Comment by shkcodes** [comment]
Any update?

**Comment by The1andONLYdave** [comment]
Didn't had time and a device to test yet, sorry. Will reply this weekend after some tests.

**Comment by The1andONLYdave** [comment]
Seems to work, Thank you! 
Downloading starts (still waiting for finish to test offline). 
Permissions working. 
No more crash on opening settings multiple times in a row.
And lyrics are displayed too :)

**Comment by shkcodes** [comment]
Cheers!
